// <auto-generated />
using System;
using LinhKienMayTinh.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BanHangMayTinh.Migrations
{
    [DbContext(typeof(LKMTdbContext))]
    [Migration("20250505071600_KhoiTaoCSDL")]
    partial class KhoiTaoCSDL
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LinhKienMayTinh.Data.CTHD", b =>
                {
                    b.Property<string>("MaHD")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaHH")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("DGBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaHD", "MaHH");

                    b.HasIndex("MaHH");

                    b.ToTable("CTHD");
                });

            modelBuilder.Entity("LinhKienMayTinh.Data.CTPhieuNhap", b =>
                {
                    b.Property<string>("MaPhieu")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaHH")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("DGNhap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaPhieu", "MaHH");

                    b.HasIndex("MaHH");

                    b.ToTable("CTPhieuNhap");
                });

            modelBuilder.Entity("LinhKienMayTinh.Data.ChamCong", b =>
                {
                    b.Property<string>("MaChamCong")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayChamCong")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoGioLamThem")
                        .HasColumnType("int");

                    b.Property<decimal>("TongLuong")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaChamCong");

                    b.HasIndex("MaNV");

                    b.ToTable("ChamCong");
                });

            modelBuilder.Entity("LinhKienMayTinh.Data.HangHoa", b =>
                {
                    b.Property<string>("MaHH")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Anh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DGBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DGNhap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HangSX")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaLoaiHH")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenHH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaHH");

                    b.HasIndex("MaLoaiHH");

                    b.ToTable("HangHoa");
                });

            modelBuilder.Entity("LinhKienMayTinh.Data.HoaDon", b =>
                {
                    b.Property<string>("MaHD")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaKH")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayLapHD")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaHD");

                    b.HasIndex("MaKH");

                    b.HasIndex("MaNV");

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("LinhKienMayTinh.Data.KhachHang", b =>
                {
                    b.Property<string>("MaKH")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaLoaiKH")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SoTienMua")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TenKH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaKH");

                    b.HasIndex("MaLoaiKH");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("LinhKienMayTinh.Data.LoaiHH", b =>
                {
                    b.Property<string>("MaLoaiHH")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLoaiHH");

                    b.ToTable("LoaiHH");
                });

            modelBuilder.Entity("LinhKienMayTinh.Data.LoaiKH", b =>
                {
                    b.Property<string>("MaLoaiKH")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("ChietKhau")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLoaiKH");

                    b.ToTable("LoaiKH");
                });

            modelBuilder.Entity("LinhKienMayTinh.Data.NhaCungCap", b =>
                {
                    b.Property<string>("MaNCC")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNCC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNCC");

                    b.ToTable("NhaCungCap");
                });

            modelBuilder.Entity("LinhKienMayTinh.Data.NhanVien", b =>
                {
                    b.Property<string>("MaNV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ChucVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("HeSoLuongThem")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LuongCoBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNV");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("LinhKienMayTinh.Data.PhieuBaoHanh", b =>
                {
                    b.Property<string>("MaPhieu")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaHH")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaKH")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<string>("TGBaoHanh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaPhieu");

                    b.HasIndex("MaHH");

                    b.HasIndex("MaKH");

                    b.HasIndex("MaNV");

                    b.ToTable("PhieuBaoHanh");
                });

            modelBuilder.Entity("LinhKienMayTinh.Data.PhieuNhap", b =>
                {
                    b.Property<string>("MaPhieu")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaNCC")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaPhieu");

                    b.HasIndex("MaNCC");

                    b.HasIndex("MaNV");

                    b.ToTable("PhieuNhap");
                });

            modelBuilder.Entity("LinhKienMayTinh.Data.TaiKhoan", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuyenHan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Username");

                    b.ToTable("TaiKhoan");
                });

            modelBuilder.Entity("LinhKienMayTinh.Data.CTHD", b =>
                {
                    b.HasOne("LinhKienMayTinh.Data.HoaDon", "HoaDon")
                        .WithMany("CTHD")
                        .HasForeignKey("MaHD")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LinhKienMayTinh.Data.HangHoa", "HangHoa")
                        .WithMany("CTHD")
                        .HasForeignKey("MaHH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HangHoa");

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("LinhKienMayTinh.Data.CTPhieuNhap", b =>
                {
                    b.HasOne("LinhKienMayTinh.Data.HangHoa", "HangHoa")
                        .WithMany("CTPhieuNhap")
                        .HasForeignKey("MaHH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LinhKienMayTinh.Data.PhieuNhap", "PhieuNhap")
                        .WithMany("CTPhieuNhap")
                        .HasForeignKey("MaPhieu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HangHoa");

                    b.Navigation("PhieuNhap");
                });

            modelBuilder.Entity("LinhKienMayTinh.Data.ChamCong", b =>
                {
                    b.HasOne("LinhKienMayTinh.Data.NhanVien", "NhanVien")
                        .WithMany("ChamCong")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("LinhKienMayTinh.Data.HangHoa", b =>
                {
                    b.HasOne("LinhKienMayTinh.Data.LoaiHH", "LoaiHH")
                        .WithMany("HangHoa")
                        .HasForeignKey("MaLoaiHH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiHH");
                });

            modelBuilder.Entity("LinhKienMayTinh.Data.HoaDon", b =>
                {
                    b.HasOne("LinhKienMayTinh.Data.KhachHang", "KhachHang")
                        .WithMany("HoaDon")
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LinhKienMayTinh.Data.NhanVien", "NhanVien")
                        .WithMany("HoaDon")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("LinhKienMayTinh.Data.KhachHang", b =>
                {
                    b.HasOne("LinhKienMayTinh.Data.LoaiKH", "LoaiKH")
                        .WithMany("KhachHang")
                        .HasForeignKey("MaLoaiKH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiKH");
                });

            modelBuilder.Entity("LinhKienMayTinh.Data.PhieuBaoHanh", b =>
                {
                    b.HasOne("LinhKienMayTinh.Data.HangHoa", "HangHoa")
                        .WithMany("PhieuBaoHanh")
                        .HasForeignKey("MaHH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LinhKienMayTinh.Data.KhachHang", "KhachHang")
                        .WithMany("PhieuBaoHanh")
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LinhKienMayTinh.Data.NhanVien", "NhanVien")
                        .WithMany("PhieuBaoHanh")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HangHoa");

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("LinhKienMayTinh.Data.PhieuNhap", b =>
                {
                    b.HasOne("LinhKienMayTinh.Data.NhaCungCap", "NhaCungCap")
                        .WithMany("PhieuNhap")
                        .HasForeignKey("MaNCC")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LinhKienMayTinh.Data.NhanVien", "NhanVien")
                        .WithMany("PhieuNhap")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhaCungCap");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("LinhKienMayTinh.Data.HangHoa", b =>
                {
                    b.Navigation("CTHD");

                    b.Navigation("CTPhieuNhap");

                    b.Navigation("PhieuBaoHanh");
                });

            modelBuilder.Entity("LinhKienMayTinh.Data.HoaDon", b =>
                {
                    b.Navigation("CTHD");
                });

            modelBuilder.Entity("LinhKienMayTinh.Data.KhachHang", b =>
                {
                    b.Navigation("HoaDon");

                    b.Navigation("PhieuBaoHanh");
                });

            modelBuilder.Entity("LinhKienMayTinh.Data.LoaiHH", b =>
                {
                    b.Navigation("HangHoa");
                });

            modelBuilder.Entity("LinhKienMayTinh.Data.LoaiKH", b =>
                {
                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("LinhKienMayTinh.Data.NhaCungCap", b =>
                {
                    b.Navigation("PhieuNhap");
                });

            modelBuilder.Entity("LinhKienMayTinh.Data.NhanVien", b =>
                {
                    b.Navigation("ChamCong");

                    b.Navigation("HoaDon");

                    b.Navigation("PhieuBaoHanh");

                    b.Navigation("PhieuNhap");
                });

            modelBuilder.Entity("LinhKienMayTinh.Data.PhieuNhap", b =>
                {
                    b.Navigation("CTPhieuNhap");
                });
#pragma warning restore 612, 618
        }
    }
}
