<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="C:\Users\PHAT TAI\.nuget\packages\nlog.config\4.7.15\contentFiles\any\any\NLog.config" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\PHAT TAI\.nuget\packages\nlog.config\4.7.15\contentFiles\any\any\NLog.config" />
    <None Remove="C:\Users\PHAT TAI\.nuget\packages\nlog.schema\5.4.0\contentFiles\any\any\NLog.xsd" />
    <None Remove="NLog.config" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="NLog.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="ClosedXML" Version="0.104.2" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="NLog" Version="5.4.0" />
    <PackageReference Include="NLog.Config" Version="4.7.15" />
    <PackageReference Include="NLog.Schema" Version="5.4.0" />
    <PackageReference Include="ReportViewerCore.NETCore" Version="15.1.26" />
    <PackageReference Include="ReportViewerCore.WinForms" Version="15.1.26" />
    <PackageReference Include="SlugGenerator" Version="2.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Reports\QLBHMayTinhDataSet.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>QLBHMayTinhDataSet.xsd</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="Reports\QLBHMayTinhDataSet.xsd">
      <Generator>MSDataSetGenerator</Generator>
      <LastGenOutput>QLBHMayTinhDataSet.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>